### ISSUE TITLE
csv_to_ins function in pest_utils: Handling non-numeric dtypes in columns of model output OTHER than first column

### ISSUE THREAD

**Issue by gmerritt123** [pypest/pyemu#149] opened 2020-07-01 12:24 UTC
Hi

If my model output file contains strings other than in the first line, and I use the csv_to_ins file to generate an ins file for it, !dum! fills each column other than the columns I specify in the 'only_cols' argument. If I call the read_output_file function using the resulting ins, I get an error. See working example below:

```
import pandas as pd
import numpy as np
import pyemu
import os

#dummy model output data 
mdl_op = pd.DataFrame(data={'LocName': {0: '1a', 1: '1b', 2: '1c', 3: '2a'},
 'X': {0: 50, 1: 50, 2: 50, 3: 40},
 'Y': {0: 50, 1: 50, 2: 50, 3: 40},
 'Z': {0: 2, 1: 28, 2: 2, 3: 26},
 'Z_Type': {0: 'Depth', 1: 'elev', 2: 'Slice', 3: 'elev'},
 'Time': {0: 'SS', 1: 'SS', 2: 'SS', 3: 'SS'},
 'Variable': {0: 'Head', 1: 'Head', 2: 'Head', 3: 'Head'},
 'Value': {0: 30.48,
  1: 30.48,
  2: 30.48,
  3: 30.63}})

#write this df to csv for csv_to_ins call
mdl_op.to_csv('Results.out',index=False)

#write ins file using this Results.out
ins_df = pyemu.pst_utils.csv_to_ins_file(csv_filename='Results.out'
                                      ,ins_filename='test.ins',only_cols=['value']
                                      ,includes_header=True)

#create InstructionFile instance using the ins file I just made
ins = pyemu.pst_utils.InstructionFile('test.ins')

#attempt to use this ins file to read Results.out
check_df = ins.read_output_file('Results.out')

```
Yields this error: 'InstructionFile error processing output file on line number 2: casting string 'depth' to float for instruction '!dum!'' 

If I do the same example but convert all but the first column to dummy numbers:

```
for col in mdl_op.columns:
    if np.issubdtype(mdl_op[col].dtype, np.number) == False and col != 'LocName':
        mdl_op.loc[:,col]=-999
```
and do the same routine as before with this updated dataframe:

```
#write this updated df  to csv for csv_to_ins call
mdl_op.to_csv('Results.out',index=False)

#write ins file using this Results.out
ins_df = pyemu.pst_utils.csv_to_ins_file(csv_filename='Results.out'
                                      ,ins_filename='test.ins',only_cols=['value']
                                      ,includes_header=True)

#create InstructionFile instance using the ins file I just made
ins = pyemu.pst_utils.InstructionFile('test.ins')

#attempt to use this ins file to read Results.out
check_df = ins.read_output_file('Results.out')
```

I get no error, and check_df yields exactly as intended - because I no longer have strings in columns other than the first column in the model output file. This workaround is not ideal as model output files can get quite large, and I feel it may be easier/better to add some sort of if statement to the csv_to_ins_file function to not use !dum! if the column is a non-numeric datatype. Also wondering how this function would handle datetime dtype as well. Not sure if this kind of implementation would throw off other intended behaviour as well. Any thoughts? Thanks...

**Comment by jtwhite79** [comment] 2020-07-01 21:16
That instruction file class tries to mimic what pest and pest++ do so it’s strict about being able to cast “dum” to a float.  But the “dum” approach (haha!) is an easy way to “count” past unused columns.  We could switch to the whitespace (“w”) instruction but that require treating the comma as a whitespace too (which pest++ can do and pest might) and this might cause trouble for datetime strings with spaces.   @briochh - does this sound reasonable?  Is it valid to just have a bunch of secondary markers for the comma chars and no “dum”s between them?

**Comment by briochh** [comment] 2020-07-01 22:03
Yes! In fact I think the changes in the feature branch `feature_pstfrom_dev` do just this. I have leaned pretty heavily on this function in the PstFrom development and made quite a few changes to the ins file.  @gmerritt123, are you able to checkout these changes on that branch a see if they work for your use-case? There will probably be a fair bit in there that isn't necessary for your case but I would (nervously) be interested to see if it also fixes (or changes) your issue.

**Comment by gmerritt123** [comment] 2020-07-02 12:40
Thanks for getting back to me @jtwhite79 

@briochh I cloned `feature_pstfrom_dev` and got same behaviour.

I drafted up two test functions in case that helps (see attached). Both of these throw an error when calling the read_output_file function on both master branch and` feature_pstfrom_dev ` . 

For the datetime tests, it looks like it does indeed parse the space in the datetime field into a date string and a time string read as separate fields. I get this error:

`Exception: InstructionFile error processing output file on line number 2: casting string '2020-07-02' to float for instruction '!dum! `
When the datetime value is `2020-07-02 08:19:32.261012`

Let me know if there's anything I can do to help. I am far from developer level in terms of managing libraries (had to install git and google how to clone your dev branch to do what you suggested), but I can write out and test functions/classes reasonably well.. just would need my hand held when it comes to versioning etc. 

[draft_tests.txt](https://github.com/pypest/pyemu/files/4864235/draft_tests.txt)

**Comment by briochh** [comment] 2020-07-02 21:26
Hi @gmerritt123, 
Thanks for the tests, that really helps. Just to clarify, do you get the same error with `read_output_file()` both `master` and `feature_pstfrom_dev` branch? From what I can see, "!dum!" shouldn't feature in the instruction file created by the `csv_to_ins_file()` method in `feature_pstfrom_dev`. -- make sure you have run `git checkout feature_pstfrom_dev` to switch branches.
For me (with `feature_pstfrom_dev`) your tests check out apart from the asserts that seem be incorrect. Should the asserts in your tests be:
```
assert check_df['obsval'].iloc[0] == mdl_op.iloc[0].Value
assert check_df['obsval'].count() == 4
```
?

**Comment by gmerritt123** [comment] 2020-07-08 15:36
Hi @briochh sorry for the delay (holidays...).

1) apologies about the assert statements being incorrect. They should be:

```
assert check_df['obsval'].iloc[0] == 30.48
assert check_df['obsval'].count() == 4
```

2) It's greatthat the tests check out on `feature_pstfrom_dev` for you (except for my poor assert statement writing). Can you just verify that these corrected asserts pass on your end, and I'll try to properly check out and import `feature_pstfrom_dev` 

Thanks for your patience!

**Comment by briochh** [comment] 2020-07-09 01:11
Hi @gmerritt123, 

Good news is that we have just merged `feature_pstfrom_dev` into the `develop` branch. Hopefully that'll will make it easier for you to access these changes in the code.

On your particular issue. We are always going to struggle set up PEST observations for entires that are not sensibly cast to float - like datetime strings. As @jtwhite79 mentioned that `read_ouput_file()` method in pyemu is trying to mimic what PEST (and PEST++) do, that is process model output floats to observations -- almost everything is PEST relies on being able to numerically describe the changes in these observations, not easy with strings and casting datetimes to floats isn't supported. Setting the `only_cols` argument to just `['value']`, your tests checkout OK - this means that the instruction file is only set up to extract the 'value' column from the model output. If you do need to track those datetimes as outputs in your PEST analysis, you might want to consider adding a post processing step that reads the raw model output (with those date time strings) and processes into a secondary output file with the datetime column converted to a numerical equivalent. This is pretty straightforward in python and the method can be added to your forward run script -- you can then use `csv_to_ins_file()` on this file instead.

Hope that helps.

**Comment by jtwhite79** [comment] 2020-07-09 02:06
I wonder if the issue is that the columns preceding the obs column(s) are not Float, so using “dum” fails, but might have varying white spaces (like date time strings) so it’s hard to use the “w” instruction.  If that is the issue, we almost need a new instruction, similar to “line advance” except it would be “column advance”, so it would skip a certain number of chars before starting to process the other instructions. But I may be misunderstanding (likely).

**Comment by briochh** [comment] 2020-07-09 02:33
I'm not sure if that is the issue in this instance, but you are right we will hit issues if whitespace delim and some entries may or may not contain whitespace. In that case, personally, the easiest solution would be to reprocess results to strip that out non-delimiting spaces (or other marker chars) or make comma delim. Column advance is starting to sound like fixed formatting and we are probably looking at a different function for this (i.e. not `csv_to_ins_file()`) with the user able to define the formatting of the output -- could get messy!

**Comment by gmerritt123** [comment] 2020-07-09 14:13
Thanks @briochh , I don't have "real" model output with datetime strings at the moment but mainly just was curious to see what would happen if I had a string with whitespace in it - I just picked datetime as a good example where it could happen. It's pretty straightforward for me to add a line or two of preprocessing to make it work I agree.

So to try and summarize: the latest dev branch will allow for strings to be in columns other than the first column, but those strings can't have whitespace? I can live with that, but probably should be documented? Am I understanding correctly? Thanks again.

**Comment by briochh** [comment] 2020-07-09 21:57
No problem @gmerritt123, If your model output file is **comma** delimited (as it is in your example test) then whitespaces in strings shouldn't be an issue; as long as they are not an output to be fed into PEST then the instruction will be to skip that column (essentially move to the next occurrence of ',').

**Closed** 2020-10-09 15:36 UTC
