### ISSUE TITLE
Using DataFrame to specify pp_space would not generate 'dat' and 'mlt' files

### ISSUE THREAD

**Issue by Paszka1** [pypest/pyemu#426] opened 2023-04-25 16:04 UTC
I am using a DataFrame to specify `pp_space` in `PstFrom.add_parameters()`. Unfortunately, neither pilot point files, nor multiplier files (in the `\mult` folder) are created by `build_pst()`. Both sets of files are, however, referenced in the `...tplfile_data.csv` and `mult2model_info.csv` files, respectively, and the return DataFrame of `PstFrom.add_parameters()` is fine. 

Otherwise, everything else looks good. Aslo template files were created.

The pilot point locations were generated internally in the script using `pp_utils.get_zoned_ppoints_for_vertexgrid()` as it is more parsimonious in generating pilot points as a result of `add_buffer`. This Data Frame info was then used to create the input DataFrame for `PstFrom.add_parameters()`. `name`, `x`, `y`, and `zone` are OK and zones are matching either. 

Am I missing something?

Shall I save the pilot points instead into a CSV file and use that for `pp_space`? Would that solve the issue?

**Comment by mnfienen** [comment] 2023-04-25 17:41
Hey @Paszka1 - can you post the code where you create the `pp_space` dataframe and you call to `.add_parameters()`? I'd be keen to see how you structured things and look for clues as to what's happening

**Comment by Paszka1** [comment] 2023-04-25 17:58
Sure @mnfienen . I put it in a function. Note that the function also includes a code section to flatten a MODFLOW6 input file into a vector format. This will require some post-processing as well. The function was created for a multi-layer DISV model to generate parameters for each layer. Something similar to the function in first the tutorial in the part 2 GMDSI tutorials but with a different purpose.

The inputs to the function:

- model: gwf instance
- files: list of input files for each layer (original structure)
- pp_pars: list of lists; on list for each layer containing spacing and bounds
- pp_dfs: it's just a list of dataframes that are only needed for plotting purposes

```
def add_mult_pars(model, files, pp_pars, pp_dfs, add_buffer=False):
    for lay, par in enumerate(pp_pars):
        ib = model.dis.idomain.array[lay]
        # Generate list of pilot points for active area of DISV grid
        pp = pyemu.utils.pp_utils.get_zoned_ppoints_for_vertexgrid(spacing=par[0],
                                                                   zone_array=ib,
                                                                   mg=model.modelgrid,
                                                                   zone_number=lay+1,
                                                                   add_buffer=add_buffer,
                                                                  )
        
        f = files[lay]
        # getting basename for parameters and parameter groups
        base = f.split(".")[1].replace("_", "") 
        # getting the pilot point name prefix (i.e., "param") from an input file's
        # name of format: "model.package_param_layer_layno.ext"
        prefix = "pp"+f.split(".")[1].split("_")[1] 
        
        # Generate dataframe for PstFrom
        name = [f'{prefix}{lay+1}_{i:04d}' for i in range(len(pp))]
        x, y = zip(*pp)
        df_sp = pd.DataFrame({"name": name,
                              "x": x,
                              "y": y,
                              "zone": (np.ones(len(pp), dtype=int) * (lay+1)).tolist()
                             }
                            )

        # Modifying the structure of the model input file into a 'vector' style file.
        # This was necessary for 'disv' grid input files as the regular file style
        # with lines isn't handled by the 'add_parameters' utility.
        ff = f"{f.split('.')[0]}.{f.split('.')[1]}_flat.txt" # name of restructured model input file
        
        d_arr = []
        with open(os.path.join(template_ws, f)) as file:
            lines = file.readlines()
            for line in lines:
                d_arr.extend(line.split())

        with open(os.path.join(template_ws, ff), 'w') as file:
            for data in d_arr:
                file.write(data)
                file.write('\n')
                
        # Add parameters
        pp_dfs[lay] = pf.add_parameters(ff,
                                        zone_array=ib,
                                        par_type="pilotpoints",
                                        geostruct=grid_gs,
                                        par_name_base=base+"pp",
                                        pargp=base+"pp",
                                        lower_bound=par[1], upper_bound=par[2],
                                        ult_lbound=par[3], ult_ubound=par[4],
                                        pp_space=df_sp,
                                       )
    return
        # Do not delete the restructured (temporary) model input file as it will be used by the multiplier
```

An example of calling the function:

```
tag = 'npf_hk'
hk_files = [f for f in os.listdir(template_ws) if tag in f.lower() and f.endswith(".txt")]
# print(hk_files)

# List with layerwise pilot point parameterization options: spacing, lower_bound, upper_bound, ult_lbound, ult_ubound
hk_pp_pars = [[2500.0, 0.25, 2.5, 0.5, 5.0],
              [2500.0, 0.25, 2.5, 0.01, 0.1],
              [2000.0, 0.10, 4.0, 1.0, 40.0],
              [5000.0, 0.25, 6.0, 0.05, 1.0],
              [5000.0, 0.20, 5.0, 0.000001, 0.00005]
             ]              
# List of parameter dataframes for ploting purposes
hk_pp_dfs = ["df_pp_hk_l1", "df_pp_hk_l2", "df_pp_hk_l3", "df_pp_hk_l4", "df_pp_hk_l5"]

add_mult_pars(gwf, hk_files, hk_pp_pars, hk_pp_dfs)
```

Please let me know if anything else is needed.

**Comment by mnfienen** [comment] 2023-04-25 18:20
@Paszka1  - ok, I have little experience with this function. Only things I can think of are:
1. There's a typo in your `add_mult_pars` function in that it takes an arg called `pp_pars` but you are getting spacing and stuff from another array called `pars`. Depending on what's in memory, you might be using a weird spacing (like 0 or some huge number). Maybe just a typo when you wrote in the browser here, but worth a look.
2. you are passing idomain (e.g. `ib`) to `get_zoned_ppoints_for_vertexgrid` which is cool, but you are also passing a `zone_number` arg which is going to be `0` for the first call and increment by `1` for each row of your `pp_pars` list of lists. But....this should limit which `ib` zones get assigned pps. Seems like it will throw an exception if you ask for a zone that's not in `ib`, so are you seeing any exceptions? In any case, that doesn't seem like what you'd want to do.

**Comment by Paszka1** [comment] 2023-04-25 18:50
Mike. The typo is not there as the pp_pars was enumerated. Regarding the zones, you are right, but for this particular problem the zones are consistent (i.e., each layer has a zone number of 1 to 5, respectively). I will definitely redo that part of the code to look professional. I do not get any errors or exceptions and the pilot points are created fine. Only those files are missing for some reason.

**Comment by Paszka1** [comment] 2023-04-26 11:04
I checked the code section again and simplified it by taking it out of the function. I am almost sure there are no bugs in it. As a result, following execution of `PstFrom.add_parameters()` I get a nice dataframe as expected. I double checked the two notes by @mnfienen, and I'm sure the typo is not there, and adding both `zone_array=ib` and `zone_number=lay+1` are required by `get_zoned_ppoints_for_vertexgrid()` as they have different roles. I.e., the `zone_array` only controls the active area where pilot points are placed, while `zone_number` actually numbers the zone, so they do not conflict with each other.

Although I don't claim that there aren't other hidden bugs somewhere in the code, I wonder if specifying a database for `pp_space` doesn't trigger a code branch in the `add_parameters()` method that skips writing the pilot point file and the multiplier file? I reiterate, that both files are referenced in other files generated by `build_pst()`.

**Comment by briochh** [comment] 2023-04-27 01:46
Hi @Paszka1, 
I am not totally across `get_zoned_ppoints_for_vertexgrid()` but I wonder, what is the format of the file that you are passing to `add_parameters()`? Is it actually array-like or is it list-like? I suspect list-like. If so, this could be at the route of the issue. The add_pars call without `index_cols` is defaulting to array-like.  

Perhaps `get_zoned_ppoints_for_vertexgrid()` is already parsing your array and extracting a table of pp locations? So maybe you need to set up using `index_cols=` (and `use_cols=`) and `par_type=grid`? To parameterise the value of every pilot point? 

Let me know if I am way off. @rhugman-intera might have some thoughts and a bit more precision to add to my wild guessing! Either way, the silent failing is a little concerning and we should address this!

**Comment by rhugman** [comment] 2023-04-27 07:57
Sounds like a bug. I dont think I made a test for passing in a ppoint DataFrame, so quite likely. I'll take a look when I get a chance.

**Comment by Paszka1** [comment] 2023-04-27 07:58
Hew @briochh,

It is array-like, but reformatted. See below.

I think I'm now closer to the source of the problem. It seems it is caused by the reformatted array-like input file in `PstFrom.add_parameters()`. The issue is that having a DISV model the standard array-like input file has an incomplete last row (4 columns against 20 in the rest), which is normal. However, `add_parameters()` expects the same number of columns. It gives an error: `ValueError: the number of columns changed from 20 to 4 at row 535; use `usecols` to select a subset and avoid this error`. At this point @jtwhite79 earlier suggested to reformat this file to a vector style array (1 column), which I've done (it is included in the body of my `add_mult_pars()` function). `add_parameters()` then handles this file and the returned dataframe looks perfect along with the pilot points, except that `build_pst()` wouldn't generate those files, and as you pointed it out it does this in a silent way.

FYI. I now skipped using `get_zoned_ppoints_for_vertexgrid()` in order to exclude it as the source of the problem.

**Comment by Paszka1** [comment] 2023-04-27 15:06
I also forgot to mention that during my test today I not only skipped using `get_zoned_ppoints_for_vertexgrid()`, but I also applied an integer spacing (i.e ., no dataframe for `pp_space`). Therefore, my humble conclusion so far is that pilot point data files aren't created as a result of using `get_zoned_ppoints_for_vertexgrid` + `pp_space=DataFrame`, while the multiplier files are not created as a result of the reformatted DISV array-like model input file. 

Hope this helps debugging and sorry for the chain posting.

**Comment by rhugman** [comment] 2023-04-28 08:42
>The `zone_array` only controls the active area where pilot points are placed, while `zone_number` actually numbers the zone, so they do not conflict with each other.

To clarify:

- `zone_number` specifies a single zone to add pilot points to. If not passed, pilot points are assigned to all zone numbers > 0 in `zone_array`.
- `zone_array` is an array of length= ncpl, with integers specifying zones.


I've tested locally, and passing in a pilot point DataFrame as multiplier style parameters seems to be working as intended with the current `develop` branch. Pilot point and `\mult` files are written after calling `.build_pst()`.

```
tag = "npf_k_"
files = [f for f in os.listdir(template_ws) if tag in f.lower() and f.endswith(".txt")]

# get the IDOMAIN array to use as zone array
ib = m.dis.idomain.get_data()

# make sure array files are tidy
for f in files:
    filename=os.path.join(template_ws, f)
    with open(filename, 'r') as f:
        a = f.read()
    a = [float(i) for i in a.split()]
    np.savetxt(fname=filename, X=a)


for f in files:
    layer = int(f.split('_layer')[-1].split('.')[0]) - 1
    
    for zn in np.unique(ib[layer]):
        pp = pyemu.utils.pp_utils.get_zoned_ppoints_for_vertexgrid(spacing=500,
                                                                zone_array=ib[layer],
                                                                mg=modelgrid,
                                                                zone_number=zn,
                                                                add_buffer=False,
                                                                )
        # Generate dataframe for PstFrom
        name = [f'pp_{i:04d}' for i in range(len(pp))]
        x, y = zip(*pp)
        df_sp = pd.DataFrame({"name": name,
                                "x": x,
                                "y": y,
                                "zone": zn
                                }
                            )
        # pilot point (medium) scale parameters
        df_pp = pf.add_parameters(f,
                            zone_array=ib[layer],
                            par_type="pilotpoints",
                            use_pp_zones=True,
                            geostruct=grid_gs,
                            par_name_base=f.split('.')[1].replace("_","")+"pp_df",
                            pargp=f.split('.')[1].replace("_","")+"pp_df",
                            lower_bound=0.2,upper_bound=5.0,
                            ult_ubound=100, ult_lbound=0.01,
                            pp_space=df_sp) 
```

**Comment by Paszka1** [comment] 2023-04-30 15:05
Thanks @rhugman for your input.

I'm completely puzzled though. I've tried using your code section in exactly the same way, and still the same problem on my end. I.e., pilot point and multipler files are not generated, but only referenced in the `mult2model_info.csv` file. Interesting that all other files such as `zone` and `var` files are created.

I've tried simplifying even more down to only parameterizing a single parameter but still the same. The only thing that resulted in a change was when using an integer for `pp_space` instead of a `dataframe`, which at least resulted in the pilot point files being created (multipliers not).

Note, that when using `par_type` `constant` or `grid` such as I'm doing for `recharge` and `maw conductance` and `maw pumping rate`, respectively, all work fine.

As I don't get any warnings or errors, I have no idea how to go forward from this point to solve the issue. Also, note that the GMDSI tutorials work fine. I also tested the code with a different simple model, and it's the same, so it isn't likely that the problem is caused by the model itself. It might, however, worth a try with the model you were testing with.

I also worked now with the `develop` version of pyEMU.

**Comment by rhugman** [comment] 2023-05-01 00:02
Sorry that didn't help @Paszka1! Can you upload your model files&script (or the simple model you refer?) so I can take a look?

**Comment by Paszka1** [comment] 2023-05-01 06:44
May I upload it to a private location (e.g., to my Dropbox account) and send you a link instead?

**Comment by rhugman** [comment] 2023-05-01 06:47
> May I upload it to a private location (e.g., to my Dropbox account) and send you a link instead?

Sure.

**Comment by Paszka1** [comment] 2023-05-01 07:28
I uploaded it to Dropbox and sent you a link to your email account at the Flinders university. 

The script looks a bit messy now as I was playing with it a lot. Some of the cells are inactivated on purpose for time saving reasons, others are tests, etc. You may reactivate the parameterization cells for recharge and the MAW wells towards the end of it, to see that those are working fine. 

Let me know if by any chance I omitted anything.

**Comment by rhugman** [comment] 2023-05-01 11:54
Thanks @Paszka1. 

- pilot point .shp files are not created by `pp_utils.get_zoned_ppoints_for_vertexgrid()` (it wasn't intended for front-end users). However, the factor and .dat files are created. Interpolation to model grid can therefore still be undertaken. If you really want the csv/shp/we, then an option would be to update `pyemu` with a `use_buffer` variable to `pp_utils.setup_pilotpoints_grid()`, this would allow the same functionality for setting up structured and vertex grid ppoints. @briochh? I am hesitant to keep adding layers of options into the code...

 - I tested with your files and the `\mult` files are not created. I have not been able to figure out why. For the Freyberg model passing in pilot point dataframes works for both dis and disv grids (see: [demo_autotest.zip](https://github.com/pypest/pyemu/files/11365144/demo_autotest.zip); please forgive the horrible code). It may be an issue/bug un-related to vertex grid?

**Comment by Paszka1** [comment] 2023-05-01 17:26
Hey @rhugman-intera ,

This is quite strange. I have added my model to be run with your code and your environment setting (i.e., `test`). It runs as expected. The same code within my environment upgraded to the same settings including the Python version will, however, fail in creating the `dat` and `\mult` files. This at least confirms that the problem is not with the model itself. But where then???

Do you think this issue may be debugged soon?

**Comment by rhugman** [comment] 2023-05-02 00:36
@jtwhite79 just pointed out to me that `\mult` files for pilot point multiplier parameters won't exist until `fac2real` is called during the preprocessing of the forward run. So it is expected that they won't be generated as part of the `PstFrom` workflow.

You can generate them on the fly using: `pyemu.helpers.apply_list_and_array_pars()` (I've tested with your files and it works) or just proceed with the workflow and call the `PstFrom` generated forward run script.

So it sounds like everything is working as intended. Hope that resolves your issue.

Cheers,
R

**Comment by briochh** [comment] 2023-08-15 22:42
@Paszka1  and @rhugman (@rhugman-intera), just following up on this. 

It looks like you got it sorted in the end. If setting up parameters with `PstFrom.add_parameters()`, files in `mult`directory will get filled/written by PEST(++) at run time (or as you worked out if you force with `pst.write_input_files()`). At runtime the multipliers in these files are applied with `pyemu.helpers.apply_list_and_array_pars()` in the forward run script (the PstFrom workflow should add this automatically to the `forward_run.py`).

**Closed by briochh** 2023-08-15 22:42 UTC
